/* Generated by tools/build-bestiary.mjs — do not edit by hand.
   Source: the 2025 Monster Manual as published in 5etools' bestiary data. */

/** Creatures in the reference document, which everyone gets. */
export const OPEN_COUNT = 330;

/** Creatures behind the password. Saying how many costs nothing; saying
    which would mean shipping them. */
export const SEALED_COUNT = 173;
